src/Entity/Fruits.php
<?php

namespace App\Entity;

use App\Repository\FruitsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FruitsRepository::class)]
class Fruits
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Occupation = null;

    #[ORM\Column(nullable: true)]
    private ?int $Age = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Evenement = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $Date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    public function getOccupation(): ?string
    {
        return $this->Occupation;
    }

    public function setOccupation(?string $Occupation): static
    {
        $this->Occupation = $Occupation;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(?int $Age): static
    {
        $this->Age = $Age;

        return $this;
    }

    public function getEvenement(): ?string
    {
        return $this->Evenement;
    }

    public function setEvenement(?string $Evenement): static
    {
        $this->Evenement = $Evenement;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(?\DateTimeInterface $Date): static
    {
        $this->Date = $Date;

        return $this;
    }
}

src/Controller/MyFruitsController.php
<?php

namespace App\Controller;

use App\Repository\FruitsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class MyFruitsController extends AbstractController{
    #[Route('/my/fruits', name: 'app_my_fruits')]
    public function index(FruitsRepository $fruitsRepository): Response
    {
        $elements = $fruitsRepository->findAll();

        return $this->render('my_fruits/index.html.twig', [
            'elements' => $elements,
        ]);
    }
}

templates/my_fruits/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un Fruit{% endblock %}

{% block body %}
{% include 'components/navbar.html.twig' %}

    <div class="container mt-5">
        <h2>Ajouter un Fruit</h2>
        
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}

        {{ form_start(form) }}
            <div class="mb-3">
                {{ form_label(form.Name) }}
                {{ form_widget(form.Name, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.Occupation) }}
                {{ form_widget(form.Occupation, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.Age) }}
                {{ form_widget(form.Age, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.Evenement) }}
                {{ form_widget(form.Evenement, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.Date) }}
                {{ form_widget(form.Date, {'attr': {'class': 'form-control'}}) }}
            </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/my_fruits/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello MyFruitsController!{% endblock %}

{% block body %}
{% include 'components/navbar.html.twig' %}

{% for element in elements %}
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{element.name}}</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">{{element.occupation}}</h6>
    <p class="card-text">{{element.age}}</p>
    <a href="#" class="card-link">{{element.evenement}}</a>
    <a href="#" class="card-link">{{element.date|date('d/m/Y')}}</a>
  </div>
</div>
    {% else %}
        <li>Aucun élément trouvé.</li>
{% endfor %}


{% endblock %}